# Generated by Django 5.2.7 on 2025-11-16 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_quiz_options_remove_quiz_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('file_url', models.URLField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='main.lesson')),
            ],
            options={
                'verbose_name_plural': '6b. Lesson Files',
            },
        ),
    ]
